steps:
# Step 1: Get credentials for the GKE cluster.
# This step fetches the credentials and stores them in the build environment.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "${_CLUSTER_NAME}" \
      --zone "${_ZONE}" \
      --project "${_PROJECT_ID}"

# Step 2: Build the Docker image.
# This builds your application's Docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest', '.']

# Step 3: Run the Python script to compile the Kubeflow pipeline.
# This step uses the image you just built to execute your pipeline script.
- name: 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']

# Step 4: Apply the compiled pipeline to Kubeflow.
# This is the step that failed. We are now explicitly setting the required
# environment variables and KUBECONFIG for the kubectl builder.
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'healthcare_ml_pipeline.yaml'
  env:
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'
  - 'KUBECONFIG=/builder/home/.kube/config'

images:
# This tells Cloud Build to automatically push the built Docker image.
- 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'

substitutions:
# Define the variables to be used throughout the build process.
  _PROJECT_ID: advance-replica-466713-n7
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
