steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubeflow-pipeline-components:latest', '.']

# Step 2: Get GKE credentials using full gcloud path
- name: 'gcr.io/$PROJECT_ID/kubeflow-pipeline-components:latest'
  entrypoint: '/usr/local/gcloud/bin/gcloud'
  args: [
    'container', 'clusters', 'get-credentials',
    '$_CLUSTER_NAME', '--zone=$_ZONE', '--project=$PROJECT_ID'
  ]

# Step 3: Compile pipeline
- name: 'gcr.io/$PROJECT_ID/kubeflow-pipeline-components:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']
  env: ['KUBECONFIG=/builder/home/.kube/config']

# Step 4: Upload pipeline
- name: 'gcr.io/$PROJECT_ID/kubeflow-pipeline-components:latest'
  entrypoint: 'kfp'
  args: [
    'pipeline', 'upload',
    '--pipeline-package', 'healthcare_ml_pipeline.yaml',
    '--pipeline-name', 'healthcare-data-ml-pipeline'
  ]
  env: ['KUBECONFIG=/builder/home/.kube/config']

images: ['gcr.io/$PROJECT_ID/kubeflow-pipeline-components:latest']

substitutions:
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
