options:
  # Add this logging option to resolve the error
  logging: CLOUD_LOGGING_ONLY
  # If you prefer bucket logging instead, use this:
  # default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
  # logs_bucket: 'gs://your-bucket-name'

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest', '.']

# Step 2: Get GKE credentials
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'container', 'clusters', 'get-credentials',
    '$_CLUSTER_NAME', '--zone=$_ZONE', '--project=$PROJECT_ID'
  ]

# Step 3: Compile pipeline
- name: 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']

# Step 4: Upload pipeline
- name: 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest'
  entrypoint: 'kfp'
  args: [
    'pipeline', 'upload',
    '--pipeline-package', 'healthcare_ml_pipeline.yaml',
    '--pipeline-name', 'healthcare-data-ml-pipeline'
  ]

images: ['gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest']

substitutions:
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
