# A Cloud Build configuration file for building and deploying a Kubeflow pipeline.

# This section configures the logs bucket. It is required when using a
# custom service account for the build.
options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
logs_bucket: 'gs://63621516867-us-central1-cloudbuild-logs'

# The steps below perform the following tasks:
# 1. Fetches GKE cluster credentials and installs the required authentication plugin.
# 2. Builds a Docker image containing the Kubeflow pipeline components.
# 3. Compiles the Kubeflow pipeline Python script into a YAML file.
# 4. Uploads the compiled pipeline YAML to the Kubeflow Pipelines UI.
steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:latest'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    # Install the gke-gcloud-auth-plugin to enable authentication for the Kubeflow SDK.
    gcloud components install gke-gcloud-auth-plugin --quiet

    # Get the credentials for the GKE cluster and store them in the Kubeconfig file.
    gcloud container clusters get-credentials "${_CLUSTER_NAME}" \
      --zone "${_ZONE}" \
      --project "${_PROJECT_ID}"

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest', '.']

- name: 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']
  env:
  - 'KUBECONFIG=/builder/home/.kube/config'

- name: 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'
  entrypoint: 'kfp'
  args:
  - 'pipeline'
  - 'upload'
  - '--pipeline-package'
  - 'healthcare_ml_pipeline.yaml'
  - '--pipeline-name'
  - 'healthcare-data-ml-pipeline'
  env:
  - 'KUBECONFIG=/builder/home/.kube/config'

# This section lists the Docker images to be pushed to Google Container Registry.
images:
- 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'

# This section defines the substitution variables used in the steps.
# You can override these variables when you trigger the build.
substitutions:
  _PROJECT_ID: advance-replica-466713-n7
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
