# This configuration file is for Google Cloud Build.
# It builds a Docker image, runs a Python script to compile a pipeline,
# and then applies it to a Kubeflow cluster.

options:
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

steps:
# Step 1: Get credentials for the GKE cluster
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "${_CLUSTER_NAME}" \
      --zone "${_ZONE}" \
      --project "${_PROJECT_ID}"

# Step 2: Build the Docker image containing your code and dependencies
# The 'images' section at the end of this file handles pushing the image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest', '.']

# Step 3: Run the Python script to compile the Kubeflow pipeline
# This step uses the image you just built, ensuring all dependencies are present.
- name: 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']

# Step 4: Apply the compiled pipeline to Kubeflow
# This step uses the built-in kubectl builder.
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'apply'
  - '-f'
  - 'healthcare_ml_pipeline.yaml'
  env:
  - 'KUBECONFIG=/builder/home/.kube/config'

images:
- 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'

substitutions:
  _PROJECT_ID: advance-replica-466713-n7
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
