steps:
  # Step 1: Configure cluster credentials
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        gcloud container clusters get-credentials ${_CLUSTER_NAME} \
          --zone ${_ZONE} \
          --project ${_PROJECT_ID}
        
        # Store kubeconfig in workspace
        mkdir -p /workspace/.kube
        cp ~/.kube/config /workspace/.kube/config

  # Step 2: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/healthcare-pipeline:latest', '.']

  # Step 3: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/healthcare-pipeline:latest']

  # Step 4: Compile and upload pipeline
  - name: 'gcr.io/$PROJECT_ID/healthcare-pipeline:latest'
    entrypoint: bash
    args:
      - '-c'
      - |
        python pipeline.py
        kfp pipeline upload -p healthcare-demo pipeline.json
        
  # Step 5: Setup observability
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud', 'monitoring', 'dashboards', 'create', '--config-from-file=observability.yaml']
    env:
      - 'KUBECONFIG=/workspace/.kube/config'

options:
  # Preserve kubeconfig between steps
  env:
    - 'KUBECONFIG=/workspace/.kube/config'

substitutions:
  _PROJECT_ID: advance-replica-466713-n7
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
