options:
  logging: CLOUD_LOGGING_ONLY
  machineType: E2_HIGHCPU_8  # More resources for compilation
  env:
    - KUBECONFIG=/builder/home/.kube/config

steps:
# Step 1: Build Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest', '.']
  waitFor: ['-']  # Start immediately

# Step 2: Get GKE credentials
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
    'container', 'clusters', 'get-credentials',
    '$_CLUSTER_NAME', '--zone=$_ZONE', '--project=$PROJECT_ID'
  ]

# Step 3: List files for debugging
- name: 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest'
  entrypoint: 'bash'
  args: ['-c', 'ls -la /app && pip list']

# Step 4: Compile pipeline
- name: 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']

# Step 5: Upload pipeline
- name: 'gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest'
  entrypoint: 'kfp'
  args: [
    'pipeline', 'upload',
    '--pipeline-package', 'healthcare_ml_pipeline.yaml',
    '--pipeline-name', 'healthcare-data-ml-pipeline'
  ]

images: ['gcr.io/$PROJECT_ID/kubeflow-healthcare-pipeline:latest']

substitutions:
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
