options:
  # This option is still a good practice, but we'll now also
  # explicitly define the logs bucket to resolve the conflict.
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET

logs_bucket: 'gs://63621516867-us-central1-cloudbuild-logs'

steps:
# Step 1: Get credentials for the GKE cluster.
# This command is still necessary and correctly fetches the auth data.
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud container clusters get-credentials "${_CLUSTER_NAME}" \
      --zone "${_ZONE}" \
      --project "${_PROJECT_ID}"

# Step 2: Build the Docker image.
# This step builds your application's Docker image.
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest', '.']

# Step 3: Run the Python script to compile the Kubeflow pipeline.
# This step uses the image you just built to execute your pipeline script.
- name: 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'
  entrypoint: 'python3'
  args: ['pipeline.py']

# Step 4: Apply the compiled pipeline to Kubeflow.
# This step is configured with the proper credentials and environment variables.
- name: 'gcr.io/cloud-builders/kubectl'
  args:
  - 'create'
  - '-f'
  - 'healthcare_ml_pipeline.yaml'
  env:
  - 'KUBECONFIG=/builder/home/.kube/config'
  - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'
  - 'CLOUDSDK_COMPUTE_ZONE=${_ZONE}'

images:
# This section tells Cloud Build to automatically push the built Docker image.
- 'gcr.io/${_PROJECT_ID}/kubeflow-pipeline-components:latest'

substitutions:
# Define the variables to be used throughout the build process.
  _PROJECT_ID: advance-replica-466713-n7
  _CLUSTER_NAME: kubeflow-healthcare-cluster
  _ZONE: us-central1-a
